"""Alexa Device Builder - generates Alexa smart_home filter configuration."""
from __future__ import annotations

import logging
import os
from typing import Any

import yaml

from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant

from .const import (
    CONF_ENTITY_NAMES,
    CONF_LOCALE,
    CONF_OPERATION_MODE,
    CONF_PACKAGE_PATH,
    DEFAULT_PACKAGE_PATH,
    DOMAIN,
    MODE_HA_YAML,
)

_LOGGER = logging.getLogger(__name__)


async def async_setup_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Set up Alexa Device Builder from a config entry."""
    operation_mode = entry.data.get(CONF_OPERATION_MODE, MODE_HA_YAML)
    if operation_mode != MODE_HA_YAML:
        _LOGGER.warning(
            "Operation mode '%s' is not active yet; skipping YAML generation",
            operation_mode,
        )
        return True

    await _write_alexa_package(hass, entry)
    entry.async_on_unload(entry.add_update_listener(_async_update_listener))
    return True


async def async_unload_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    """Unload a config entry."""
    return True


async def async_remove_entry(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Remove a config entry and delete the generated package file."""
    package_path = entry.data.get(CONF_PACKAGE_PATH, DEFAULT_PACKAGE_PATH)
    full_path = hass.config.path(package_path)
    await hass.async_add_executor_job(_remove_yaml, full_path)


async def _async_update_listener(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Handle options update."""
    await _write_alexa_package(hass, entry)


async def _write_alexa_package(hass: HomeAssistant, entry: ConfigEntry) -> None:
    """Write the Alexa package YAML file."""
    options = entry.options
    package_path = entry.data.get(CONF_PACKAGE_PATH, DEFAULT_PACKAGE_PATH)
    full_path = hass.config.path(package_path)
    _LOGGER.debug("Writing Alexa package to %s", full_path)
    await hass.async_add_executor_job(_write_yaml, full_path, dict(options))


def _write_yaml(full_path: str, options: dict[str, Any]) -> None:
    """Write YAML file (blocking I/O, run in executor)."""
    include_entities: list[str] = options.get("include_entities", [])
    include_domains: list[str] = options.get("include_domains", [])
    exclude_entities: list[str] = options.get("exclude_entities", [])
    exclude_domains: list[str] = options.get("exclude_domains", [])
    entity_names: dict[str, str] = options.get(CONF_ENTITY_NAMES, {})
    locale: str | None = options.get("locale") or None  # empty string means "not set"

    lines = [
        "# Generated by Alexa Device Builder - do not edit manually",
        "alexa:",
        "  smart_home:",
    ]

    if locale:
        lines.append(f"    locale: {locale}")

    filter_lines: list[str] = []
    if include_entities:
        filter_lines.append("      include_entities:")
        filter_lines.extend(f"        - {e}" for e in sorted(include_entities))
    if include_domains:
        filter_lines.append("      include_domains:")
        filter_lines.extend(f"        - {d}" for d in sorted(include_domains))
    if exclude_entities:
        filter_lines.append("      exclude_entities:")
        filter_lines.extend(f"        - {e}" for e in sorted(exclude_entities))
    if exclude_domains:
        filter_lines.append("      exclude_domains:")
        filter_lines.extend(f"        - {d}" for d in sorted(exclude_domains))

    if filter_lines:
        lines.append("    filter:")
        lines.extend(filter_lines)
    elif not entity_names:
        lines.append(
            "    # No filter configured - all entities are exposed to Alexa"
        )

    if entity_names:
        lines.append("    entity_config:")
        for entity_id, name in sorted(entity_names.items()):
            lines.append(f"      {entity_id}:")
            yaml_lines = yaml.dump(
                {"name": name},
                allow_unicode=True,
                explicit_start=False,
                explicit_end=False,
            ).splitlines()
            if yaml_lines and yaml_lines[0].strip() == "---":
                yaml_lines = yaml_lines[1:]
            if yaml_lines and yaml_lines[-1].strip() == "...":
                yaml_lines = yaml_lines[:-1]
            if not yaml_lines:
                _LOGGER.warning("Could not render name for %s, writing empty name", entity_id)
                yaml_lines = ["name: ''"]
            lines.extend(f"        {line}" for line in yaml_lines)

    dir_path = os.path.dirname(full_path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)

    non_blank_lines = [line for line in lines if line.strip()]

    with open(full_path, "w", encoding="utf-8") as f:
        f.write("\n".join(non_blank_lines) + "\n")

    _LOGGER.info("Alexa package file written to %s", full_path)


def _remove_yaml(full_path: str) -> None:
    """Remove the generated YAML file (blocking I/O, run in executor)."""
    try:
        os.remove(full_path)
        _LOGGER.info("Removed Alexa package file: %s", full_path)
    except FileNotFoundError:
        pass
    except OSError as err:
        _LOGGER.warning(
            "Could not remove Alexa package file %s: %s", full_path, err
        )
